# Generated by Django 3.2.12 on 2023-12-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_auto_20231219_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmission',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
