# Generated by Django 3.2.12 on 2023-12-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_task_incentives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='incentives',
            field=models.TextField(blank=True, default='no incentive🤡'),
        ),
    ]
