# Generated by Django 3.2.12 on 2023-12-28 10:49

import Task.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0004_auto_20231221_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Task.models.upload_to),
        ),
    ]
