# Generated by Django 3.2.12 on 2023-12-29 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0003_alter_task_incentives'),
        ('Task', '0005_task_image'),
    ]

    operations = [
    ]
