# Generated by Django 3.2.12 on 2023-12-29 12:47

import Task.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0005_task_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmission',
            name='image',
            field=models.ImageField(blank=True, help_text='Image of the Task Submission', null=True, upload_to=Task.models.sumbission_upload_to),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, help_text='Description for the Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, help_text='Image for the Task', null=True, upload_to=Task.models.upload_to),
        ),
        migrations.AlterField(
            model_name='task',
            name='points',
            field=models.IntegerField(default=0, help_text='Points for the Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(help_text='Title for the Task', max_length=255),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='admin_comment',
            field=models.TextField(blank=True, help_text='Admin Comment for the Task Submission', null=True),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='link',
            field=models.URLField(blank=True, help_text='Link to the Task Submission', null=True),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='verified',
            field=models.BooleanField(default=False, help_text='Whether the Task Submission is Verified'),
        ),
    ]
