# Generated by Django 3.2.12 on 2023-12-29 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0006_auto_20231229_1817'),
        ('Task', '0006_merge_0003_alter_task_incentives_0005_task_image'),
    ]

    operations = [
    ]
