# Generated by Django 3.2.12 on 2024-02-01 20:01

import Task.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0008_auto_20240106_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksubmission',
            name='image',
            field=models.ImageField(blank=True, help_text='Image of the Task Submission', max_length=255, null=True, upload_to=Task.models.sumbission_upload_to),
        ),
    ]
