# Generated by Django 4.2.6 on 2023-10-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('role', models.IntegerField(choices=[(3, 'Admin'), (2, 'Staff'), (1, 'User')], default=1)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('V', 'Verified'), ('D', 'Deleted')], default='P', max_length=1)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('phone_no', models.CharField(max_length=10)),
                ('whatsapp_no', models.CharField(max_length=10)),
                ('postal_address', models.TextField()),
                ('pin_code', models.IntegerField()),
                ('why_choose', models.TextField()),
                ('were_you_ca', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
