# Generated by Django 4.2.6 on 2023-10-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Authentication", "0003_remove_useraccount_college_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="user_name",
            field=models.CharField(default="default", max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
