# Generated by Django 4.2.6 on 2023-10-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_userprofile_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='referral_code',
            field=models.CharField(default='none', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
