# Generated by Django 3.2.12 on 2023-10-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0007_userpasswordforgototp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpasswordforgototp',
            name='has_been_used',
            field=models.BooleanField(default=False),
        ),
    ]
