# Generated by Django 3.2.12 on 2023-10-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0007_verificationmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='status',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('V', 'Verified'), ('D', 'Deleted')], default='P', max_length=1),
        ),
    ]
