# Generated by Django 3.2.12 on 2023-10-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Authentication", "0009_userpasswordforgototp_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpasswordforgototp",
            name="last_created",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
