# Generated by Django 3.2.12 on 2023-12-04 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0009_useraccount_email_verified'),
        ('Authentication', '0010_userpasswordforgototp_last_created'),
    ]

    operations = [
    ]
