# Generated by Django 3.2.12 on 2023-12-16 09:55

from uuid import uuid4
from django.db import migrations


class Migration(migrations.Migration):

    def populate_uuid(apps, schema_editor):
        user_profile = apps.get_model('Authentication', 'UserProfile')
        users = list(user_profile.objects.all())
        for user in users:
            user.unique_id = uuid4()
        user_profile.objects.bulk_update(users, ['unique_id'])

    dependencies = [
        ('Authentication', '0013_userprofile_unique_id'),
    ]

    operations = [
        migrations.RunPython(populate_uuid)
    ]
