# Generated by Django 3.2.12 on 2023-12-18 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0014_auto_20231216_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPasswordOTPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6, unique=True)),
                ('has_been_used', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('last_created', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
