# Generated by Django 3.2.12 on 2023-12-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0015_forgotpasswordotpmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_id',
            field=models.IntegerField(default=1),
        ),
    ]
