# Generated by Django 3.2.12 on 2023-12-24 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0016_userprofile_avatar_id'),
    ]

    def populate_referral_codes(apps, schema_editor):
        ReferralCode = apps.get_model('Authentication', 'ReferralCode')
        UserAccount = apps.get_model('Authentication', 'UserAccount')
        UserProfile = apps.get_model('Authentication', 'UserProfile')
        for user in UserAccount.objects.all():
             profile = UserProfile.objects.filter(user=user).first()
             if profile:
              ReferralCode.objects.create(user=user, referral_code=f"technex24_{user.username}_{profile.first_name}_{profile.last_name}")

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='referral_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='unique_id',
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(max_length=50, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(populate_referral_codes),
    ]
