# Generated by Django 3.2.12 on 2024-01-14 12:19

from django.db import migrations
import uuid

def populate_verification_model(apps, schema_editor):
    Verif = apps.get_model('Authentication', 'VerificationModel')
    User = apps.get_model('Authentication', 'UserAccount')
    for user in User.objects.all():
        verif, created = Verif.objects.get_or_create(userid = user)
        if verif:
            verif.email_token = uuid.uuid4()
            verif.save()

class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0018_auto_20240104_2247'),
    ]

    operations = [
        migrations.RunPython(populate_verification_model),
    ]
