# Generated by Django 3.2.12 on 2024-01-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0019_auto_20240114_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='referrals',
            field=models.IntegerField(default=0),
        ),
    ]
