# Generated by Django 3.2.12 on 2024-01-26 16:52

from django.conf import settings
from django.db import migrations
import uuid
from ..send_email import send_email_verif_email
from decouple import config
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.image import MIMEImage
import smtplib
import os

def resend_email_verif_email(apps, schema_editor):
    LOGO_FILE_PATH = os.path.join(settings.STATIC_ROOT, 'Asset 3.png')
    SUPPORT_EMAIL = config("SUPPORT_EMAIL", default="tech@technex.in")
    User = apps.get_model('Authentication', 'UserAccount')
    VerifModel = apps.get_model('Authentication', 'VerificationModel')
    connection = smtplib.SMTP("smtp.gmail.com", 587)
    connection.starttls()
    connection.ehlo_or_helo_if_needed()
    connection.login(config("EMAIL_HOST_USER"), config("EMAIL_HOST_PASSWORD"))

    for user in User.objects.all():
        if not user.email_verified:
            token, created = VerifModel.objects.get_or_create(userid=user, defaults={'email_token': uuid.uuid4()})
            token = token.email_token
            print("Sending email to", user.username)
            rec_email = user.email
            username = user.username
            msg = MIMEMultipart()
            msg['From'] = config("EMAIL_HOST_USER")
            msg['To'] = rec_email
            msg['Subject'] = "Technex'24 - Email Verification"
            # Use images and style the email
            
            html = f"""\
            <html>
                <head></head>
                <body>
                <center><img src="cid:logo" alt="Technex '24" border="0" width="200" height="200"></center>
                    <h3>Dear {username},</h3>
                    <br>
                    <p>Congratulations! Your account on Technex'24 has been successfully created. It has come to our notice that many users have not received this email verification email. Please click on the following button to confirm and activate your account</p>
                    <br>
                    <center><a href="{config('BACKEND_URL')}/auth/verifyemail/{token}/"><button style="background-color: #4CAF50; border: none; color: white; padding: 15px 32px; text-align: center; text-decoration: none; display: inline-block; cursor: pointer;">Verify Email</button></a></center>
                    <br>
                    <p>If you encounter any issues or have any questions, feel free to reach out to our support team at {SUPPORT_EMAIL}.</p>
                    <p>Best regards,</p>
                    <p>CA Team - Technex'24</p>

                    PS: If you are unable to click the button, copy and paste the following link in your browser: {config('BACKEND_URL')}/auth/verifyemail/{token}/
                </body>
            </html>
            """
            body = html
            msg.attach(MIMEText(body, 'html'))
            if os.path.exists(LOGO_FILE_PATH):
                with open(LOGO_FILE_PATH, 'rb') as fp:
                    img = MIMEImage(fp.read())
            img.add_header('Content-ID', '<logo>')
            img.add_header('Content-Disposition', 'inline')
            msg.attach(img)
    
            msg = msg.as_string()
            
            connection.sendmail(config("EMAIL_HOST_USER"), rec_email, msg)
        
    connection.quit()
            
        

class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0020_userprofile_referrals'),
    ]

    operations = [
        migrations.RunPython(resend_email_verif_email),
    ]